# Generated by Django 3.1.5 on 2021-07-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictList',
            fields=[
                ('district_id', models.IntegerField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=100)),
                ('state_id', models.IntegerField()),
            ],
            options={
                'db_table': 'districtlist',
            },
        ),
        migrations.CreateModel(
            name='StatesList',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'statelist',
            },
        ),
    ]
