# Generated by Django 3.2.5 on 2021-07-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowin', '0003_auto_20210720_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='filter',
            name='age',
            field=models.IntegerField(choices=[(18, '18+'), (45, '45+')], default=None),
        ),
        migrations.AlterField(
            model_name='filter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='pincode',
            field=models.IntegerField(default=None),
        ),
    ]
