# Generated by Django 3.2.5 on 2021-07-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowin', '0004_auto_20210721_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilter',
            name='age',
            field=models.IntegerField(choices=[(18, '18+'), (45, '45+')], default=None),
        ),
        migrations.AddField(
            model_name='userfilter',
            name='pincode',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='userfilter',
            name='vaccine_name',
            field=models.CharField(choices=[('covaxin', 'Covaxin'), ('covishield', 'CoviShield'), ('sputnik', 'Sputnik')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='userfilter',
            name='vaccine_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default=None, max_length=100),
        ),
    ]
