# Generated by Django 3.2.5 on 2021-07-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowin', '0005_auto_20210721_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilter',
            name='vaccine_name',
            field=models.CharField(choices=[('COVAXIN', 'Covaxin'), ('COVISHIELD', 'CoviShield'), ('sputnik', 'Sputnik')], default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
